### ISSUE TITLE
Can point to the github URL? 

### ISSUE THREAD

**Issue by velara3** [pklaschka/xd-manifest-schema#3]
In the readme the URL is pointing to your website but it looks like there is a schema.json here in the repository. Which one should I link to? Also, if I want to download the config where do I place it in VSCode?

Refs:
https://github.com/pklaschka/xd-manifest-schema
https://raw.githubusercontent.com/pklaschka/xd-manifest-schema/master/schema.json

**Comment by pklaschka** [comment]
Hi @velara3,

either should be fine (I always keep the one on my website up-to-date with the latest version, so I'd recommend that one). The reason for having it on my website is that there, I can guarantee that the URL stays the same as long as it exists (which – for a schema like this – is vital, of course). With the GitHub link, I can't guarantee that the URL scheme won't change (I think it's unlikely, but you're simply on the "safe side" by using the one from my domain).

As for the VSCode question: You'll have to insert the code snippet
```
"json.schemas": [
    {
      "fileMatch": [
        "/Adobe/*/develop/*/manifest.json"
      ],
      "url": "https://xdplugins.pabloklaschka.de/xsd/xd-manifest.json"
    }
  ]
```
in your `settings.json` file (as described in the README). There is – to my knowledge – no way to download a config or set this up on a per-project basis (I only know of this one way to set it up globally via the settings).

I hope this answers your question 😉
